### PR TITLE
Integral fix

### LINKED ISSUE #198: BoundsIntegral performance improvement
## Describe the problem or improvement suggested
Right now, the complete history of bounds is stored in the event handler and the integral is recomputed from start before taking a difference.

## Describe the solution you would like
Only store the values since the last call to `extract` and compute directly the integral difference from this.
Something like
```cpp
auto const& primal_bounds = ...

auto inegral = Reward{0.};
if(...){
    integral = compute_primal_integral(primal_bounds);
} else {
    ...
}

handler.clear_all_but_last();
// No need to compute diff anymore
return integral;
```

## Additional context
#144

### LINKED ISSUE #202: Primal / dual integral code review
Why not using a logical OR (&) to check for event types, as the SCIP codebase does ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L133
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L137

Shouldn't we check for the objective direction here ? (minimization vs maximization instances)
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L101
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L118
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L245

Won't this cause an issue if more that one bound reward function objects are used within an environment ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L214

Could the event handler pointer be returned here ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L249

The initial primal bound here should not be needed:
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L165

~~Shouldn't we use the initial dual bound here ?~~
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L170

~~Same here, shouldn't we use the initial primal bound instead ?~~
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L186

### PR DESCRIPTION
**Pull request by jdumouchelle**
## Pull request checklist

- [x] I have opened an issue to discuss the proposed changes: Fix #202 #198.
- [x] I have modified/added tests to cover the new changes/features.
- [x] I have modified/added the documentation to cover the new changes/features.
- [x] I have ran the tests, checks, and code formatters.

## Proposed implementation

Fixed issues as @gasse suggested in #202 and resolved #198.  The only issue left to resolve is how we can deal with the naming of the event handlers when there are multiple.  I will open a separate issue so it can be discussed.

### CODE REVIEW

**Comment by jdumouchelle** [comment]
I made a quick fix for allowing the inclusion of multiple integral reward functions in an environment, i.e. a fix for #205.   It is done by keeping a counter and defining the name based on the value of the counter.  Each time a reward function is initialize the counter is incremented.   The name is stored in the `BoundIntegral` class as a member so it can be retrieved on `extract()`.  If anyone has cleaner suggestions on how to do this then feel free to make suggestions.  

Anyway, this branch resolves the issues pointed out by @gasse so it should be in a good place to merge back to `dev`.

File: libecole/src/reward/boundintegral.cpp [hunk 1]
```diff
@@ -196,92 +240,128 @@ auto compute_primal_dual_integral(
...
+ecole::reward::BoundIntegral<bound>::BoundIntegral(bool wall_, const BoundFunction& bound_function_) : wall{wall_} {
+	if constexpr (bound == Bound::dual) {
+		bound_function = bound_function_ ? bound_function_ : default_dual_bound_function;
+	} else if constexpr (bound == Bound::primal) {
+		bound_function = bound_function_ ? bound_function_ : default_primal_bound_function;
+	} else if constexpr (bound == Bound::primal_dual) {
+		bound_function = bound_function_ ? bound_function_ : default_primal_dual_bound_function;
+	}
+	name = IntegralEventHandler::base_name + std::to_string(IntegralEventHandler::integral_reward_function_counter);
+	IntegralEventHandler::integral_reward_function_counter++;
```
Comment (AntoinePrv) [inline libecole/src/reward/boundintegral.cpp:321]: Should we add a lock here? (see `Scimpl::copy` for an example).

Comment (jdumouchelle) [reply libecole/src/reward/boundintegral.cpp:321]: Yea I think it makes sense to add one here.  It might not really be needed since different threads would have different instances, leading to no name conflicts, but I think it is more intuitive to make each reward function have a uniquely named event handler anyway.

Comment (gasse) [reply libecole/src/reward/boundintegral.cpp:321]: I think ++ should is an atomic operation for ints...
Maybe using std::atomic would make sure of it ?
https://en.cppreference.com/w/cpp/atomic/atomic

Comment (jdumouchelle) [reply libecole/src/reward/boundintegral.cpp:325]: I don't think that would resolve the case where two threads give `name` the same value since it could be the case that ++ may not be called in either thread right?

File: libecole/src/reward/boundintegral.cpp [hunk 2]
```diff
@@ -155,21 +163,48 @@ void IntegralEventHandler::extract_metrics(SCIP* scip, SCIP_EVENTTYPE event_type
 	times.push_back(time_now(wall));
 }
 
+void IntegralEventHandler::clear_bounds() {
+	if (extract_dual) {
+		auto last_dual = dual_bounds[dual_bounds.size() - 1];
```
Comment (gasse) [inline libecole/src/reward/boundintegral.cpp:168]: Equivalently, you can use `dual_bounds.back()` here.

File: libecole/src/reward/boundintegral.cpp [hunk 3]
```diff
@@ -155,21 +163,48 @@ void IntegralEventHandler::extract_metrics(SCIP* scip, SCIP_EVENTTYPE event_type
...
+		dual_bounds.clear();
+		dual_bounds.push_back(last_dual);
+	}
+	if (extract_primal) {
+		auto last_primal = primal_bounds[primal_bounds.size() - 1];
```
Comment (gasse) [inline libecole/src/reward/boundintegral.cpp:173]: Equivalently, you can use `primal_bounds.back()` here.

File: libecole/src/reward/boundintegral.cpp [hunk 4]
```diff
@@ -155,21 +163,48 @@ void IntegralEventHandler::extract_metrics(SCIP* scip, SCIP_EVENTTYPE event_type
...
+		primal_bounds.clear();
+		primal_bounds.push_back(last_primal);
+	}
+	auto last_time = times[times.size() - 1];
```
Comment (gasse) [inline libecole/src/reward/boundintegral.cpp:177]: Equivalently, you can use `times.back()` here.

File: libecole/src/reward/boundintegral.cpp [hunk 5]
```diff
@@ -155,21 +163,48 @@ void IntegralEventHandler::extract_metrics(SCIP* scip, SCIP_EVENTTYPE event_type
...
+			dual_integral += dual_bound_diff * time_diff;
+		}
+	} else {
+		for (std::size_t i = 0; i < dual_bounds.size() - 1; ++i) {
+			auto const db = std::min(dual_bounds[i], initial_dual_bound);
+			auto const dual_bound_diff = db - offset;
+			auto const time_diff = std::chrono::duration<double>(times[i + 1] - times[i]).count();
+			dual_integral += dual_bound_diff * time_diff;
+		}
 	}
```
Comment (gasse) [inline libecole/src/reward/boundintegral.cpp:208]: I don't like the variable name `dual_bound_diff` here. `time_diff` is, indeed, a time difference, but `dual_bound_diff` is not a dual bound difference. What about something like:
```suggestion
	for (std::size_t i = 0; i < dual_bounds.size() - 1; ++i) {
		auto const time_diff = std::chrono::duration<double>(times[i + 1] - times[i]).count();
		auto const dual_bound = dual_bounds[i];
		if (obj_sense == SCIP_OBJSENSE_MINIMIZE) {
			dual_integral += -(std::max(dual_bound, initial_dual_bound) - offset) * time_diff;
		} else {
			dual_integral += (std::min(dual_bound, initial_dual_bound) - offset) * time_diff;
		}
	}
```

File: libecole/src/reward/boundintegral.cpp (hunk 1 above)
Comment (gasse) [reply libecole/src/reward/boundintegral.cpp:325]: Never mind, the whole action of reading and then incrementing the counter should be atomic. Looks good now.

**Review by gasse — CHANGES_REQUESTED** [review]
Except for a few comments, looks good to me.

**Comment by jdumouchelle** [comment]
Thanks for the feedback @gasse and @AntoinePrv.  I have made all of the suggested changes.  Let me know if there is anything else, otherwise I think it is good to merge.

File: libecole/src/reward/boundintegral.cpp [hunk 6]
```diff
@@ -100,7 +103,10 @@ auto get_primal_bound(SCIP* scip) {
 	case SCIP_STAGE_SOLVED:
 		return SCIPgetPrimalbound(scip);
 	default:
-		return SCIPinfinity(scip);
+		if (SCIPgetObjsense(scip) == SCIP_OBJSENSE_MINIMIZE) {
+			return SCIPinfinity(scip);
+		}
+		return -SCIPinfinity(scip);
```
Comment (gasse) [inline libecole/src/reward/boundintegral.cpp:109]: A detail, but possible will save us some future trouble. To be consistent with `SCIPgetPrimalbound`, we should get instead here the objective limit, which will be SCIP's infinity if it has not been set. See [`SCIPgetObjlimit`](https://www.scipopt.org/doc/html/scip__prob_8c_source.php#l01490). This also simplifies the code a bit.

Comment (jdumouchelle) [reply libecole/src/reward/boundintegral.cpp]: Thanks for the suggestion, I made the change.  I don't believe there is a dual bound equivalent to this right?  I just left the dual bound function as is.

Comment (gasse) [reply libecole/src/reward/boundintegral.cpp]: Yes I think that's only for the primal bound unfortunately...

**Comment by gasse** [comment]
Great, looks good to me !

**Review by gasse — APPROVED** [review]
